### ISSUE TITLE
 java.lang.RuntimeException: Buffer not large enough for pixels                                                                                                     	at android.graphics.Bitmap.copyPixelsFromBuffer(Bitmap.java:676)                                                                                                     	at io.github.crow_misia.libyuv.BufferExtKt.toBitmap(BufferExt.kt:9)                                                                                                     	at io.github.crow_misia.libyuv.AbgrBuffer.asBitmap(AbgrBuffer.kt:18)

### ISSUE THREAD

**Issue by whereareu** [crow-misia/libyuv-android#27]

**Comment by crow-misia** [comment]
AbgrBufferをどのように作成しましたか？
Planeから変換(wrapメソッドを使用)した場合、PlaneがABGRフォーマットである必要があります。
